apiVersion: apps/v1
kind: Deployment
metadata:
  name: address
  labels:
    api: address
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      api: address
      version: "1"
  template:
    metadata:
      name: address
      labels:
        api: address
        version: "1"
    spec:
      containers:
        - name: address
          image: parameshg/northwind.address:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80