apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-3
  labels:
    api: address
    version: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      api: address
      version: "3"
  template:
    metadata:
      name: address-3
      labels:
        api: address
        version: "3"
    spec:
      containers:
        - name: address
          image: parameshg/northwind.address:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80