apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    api: product
spec:
  type: ClusterIP
  selector:
    api: product
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80