apiVersion: v1
kind: Service
metadata:
  name: address
  labels:
    api: address
spec:
  type: ClusterIP
  selector:
    api: address
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80