apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment
spec:
  host: payment
  subsets:
    - name: v1
      labels:
        version: "1"
    - name: v2
      labels:
        version: "2"