apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: address
spec:
  host: address
  subsets:
    - name: v1
      labels:
        api: address
        version: "1"
    - name: v2
      labels:
        api: address
        version: "2"
    - name: v3
      labels:
        api: address
        version: "3"