apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment
spec:
  hosts:
    - payment
  http:
    - route:
      - destination:
          host: payment
          subset: v1
        weight: 10
      - destination:
          host: payment
          subset: v2
        weight: 90
