apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: address
spec:
  hosts:
    - address
  http:
    - route:
      - destination:
          host: address
          subset: v1
        weight: 80
      - destination:
          host: address
          subset: v2
        weight: 20